### ISSUE TITLE
gitpages cannot access echarts.js by http

### ISSUE THREAD

**Issue by JackEggie** [quentin-chen/hexo-tag-echarts3#2]
在template.html中通过http的方式引入echarts.js。

```
<script src="http://echarts.baidu.com/dist/echarts.common.min.js"></script>
```

然而在gitpages和coding pages都是通过https访问的，会在浏览器控制台直接报错。

能不能使用https的源呢？[https://echarts.baidu.com/dist/echarts.common.min.js](https://echarts.baidu.com/dist/echarts.common.min.js)也是可以直接访问的。

**Comment by kchen0x** [comment]
我刚才看了一下，echarts并没有提供有效证书，
https://echarts.baidu.com/dist/echarts.common.min.js
这个地址的文件是会被chrome标记为危险的。

**Comment by JackEggie** [comment]
确实是这样子，chrome仍然会block掉这个js，作者有没有更好的方案可以在github pages上使用echarts的js文件呢？

**Comment by 0x1428571429** [comment]
https 不能正常使用该插件都问题已经修复
https://alili.tech/2018/09/01/Data%20analysis/2018%E5%B9%B409%E6%9C%88%E5%9B%BD%E5%86%85%E6%B5%8F%E8%A7%88%E5%99%A8%E6%95%B0%E6%8D%AE%E7%BB%9F%E8%AE%A1/

**Comment by JackEggie** [comment]
@kchen0x 是否需要升级个小版本，并发布到npm仓库呢，否则npm update拉到的代码还是旧的。

**Comment by kchen0x** [comment]
@JackEggie  已经更新并发布到 npm 仓库
版本号 1.1.2
